# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\xb5\x01\n\x12GetDeptUserRequest\x12\x0f\n\x07\x64\x65pt_id\x18\x01 \x01(\r\x12\x11\n\tdept_name\x18\x02 \x01(\t\x12\x10\n\x08uid_list\x18\x03 \x03(\r\x12:\n\x06\x66ilter\x18\x04 \x03(\x0b\x32*.helloworld.GetDeptUserRequest.FilterEntry\x1a-\n\x0b\x46ilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\tBasicUser\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xc6\x01\n\x13GetDeptUserResponse\x12(\n\tuser_list\x18\x01 \x03(\x0b\x32\x15.helloworld.BasicUser\x12>\n\x08user_map\x18\x02 \x03(\x0b\x32,.helloworld.GetDeptUserResponse.UserMapEntry\x1a\x45\n\x0cUserMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.helloworld.BasicUser:\x02\x38\x01\x32[\n\x07Greeter\x12P\n\x0bGetDeptUser\x12\x1e.helloworld.GetDeptUserRequest\x1a\x1f.helloworld.GetDeptUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETDEPTUSERREQUEST_FILTERENTRY._options = None
  _GETDEPTUSERREQUEST_FILTERENTRY._serialized_options = b'8\001'
  _GETDEPTUSERRESPONSE_USERMAPENTRY._options = None
  _GETDEPTUSERRESPONSE_USERMAPENTRY._serialized_options = b'8\001'
  _GETDEPTUSERREQUEST._serialized_start=33
  _GETDEPTUSERREQUEST._serialized_end=214
  _GETDEPTUSERREQUEST_FILTERENTRY._serialized_start=169
  _GETDEPTUSERREQUEST_FILTERENTRY._serialized_end=214
  _BASICUSER._serialized_start=216
  _BASICUSER._serialized_end=253
  _GETDEPTUSERRESPONSE._serialized_start=256
  _GETDEPTUSERRESPONSE._serialized_end=454
  _GETDEPTUSERRESPONSE_USERMAPENTRY._serialized_start=385
  _GETDEPTUSERRESPONSE_USERMAPENTRY._serialized_end=454
  _GREETER._serialized_start=456
  _GREETER._serialized_end=547
# @@protoc_insertion_point(module_scope)
